name: assignment1
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  web: any
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets_lzj/
    - assets_lzj/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets_lzj/fonts/MontserratBold.ttf
          weight: 700
        - asset: assets_lzj/fonts/MontserratSemiBold.ttf
          weight: 600
